# Generated by Django 5.1.4 on 2025-01-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('gdp', models.DecimalField(decimal_places=2, help_text='GDP in USD (Trillions)', max_digits=12)),
                ('work_hours', models.IntegerField(help_text='Average work hours per week')),
                ('literacy_rate', models.DecimalField(decimal_places=2, help_text='Percentage of literacy rate', max_digits=5)),
                ('top_universities_count', models.IntegerField(help_text='Number of universities in top global rankings')),
                ('education_quality_index', models.DecimalField(decimal_places=2, help_text='Education quality index (1-100)', max_digits=5)),
                ('living_cost_index', models.DecimalField(decimal_places=2, help_text='Living cost index (1-100)', max_digits=5)),
                ('average_tuition_fees', models.DecimalField(decimal_places=2, help_text='Average tuition fees (USD)', max_digits=10)),
                ('work_permit_availability', models.BooleanField(default=False, help_text='Can international students work while studying?')),
                ('post_study_work_visa_duration', models.IntegerField(blank=True, help_text='Post-study work visa duration in months', null=True)),
                ('safety_index', models.DecimalField(decimal_places=2, help_text='Safety index (1-100)', max_digits=5)),
                ('health_care_index', models.DecimalField(decimal_places=2, help_text='Healthcare quality index (1-100)', max_digits=5)),
                ('climate_type', models.CharField(choices=[('Tropical', 'Tropical'), ('Dry', 'Dry'), ('Temperate', 'Temperate'), ('Continental', 'Continental'), ('Polar', 'Polar')], help_text='Type of climate', max_length=50)),
                ('average_temperature', models.DecimalField(decimal_places=2, help_text='Average annual temperature (°C)', max_digits=5)),
                ('language', models.CharField(help_text='Primary language(s) spoken', max_length=100)),
                ('currency', models.CharField(help_text='Currency used', max_length=50)),
                ('timezone', models.CharField(help_text='Timezone(s)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
