# Generated by Django 5.1.4 on 2025-01-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0003_rename_course_level_studypreferences_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseLevel',
            new_name='Faculty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='course.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='course_images/'),
        ),
    ]
