# Generated by Django 5.1.4 on 2025-01-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_level_education', models.CharField(max_length=100)),
                ('year_of_completion', models.CharField(max_length=4)),
                ('country_of_education', models.CharField(max_length=100)),
                ('obtained_marks', models.CharField(max_length=10)),
                ('no_of_backlogs', models.CharField(max_length=10)),
                ('education_gap', models.IntegerField()),
                ('gap_reason', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_backgrounds', to='user.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_intake', models.CharField(max_length=50)),
                ('course_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courselevel')),
                ('preferred_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_preferences', to='user.student')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
