# Generated by Django 5.1.4 on 2025-01-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_educationbackground_studypreferences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studypreferences',
            old_name='course_level',
            new_name='faculty',
        ),
    ]
