# Generated by Django 5.1.4 on 2025-01-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_basicinfo_contact_remove_educationbackground_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
