# Generated by Django 5.1.4 on 2025-01-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_maritalstatus_basicinfo_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
